# See https://openmod.github.io/openmod-docs/devdoc/concepts/configuration.html
# You can delete this file if you do not need a configuration

join_messages: true
join_announcements: true

leave_messages: true
leave_announcements: true

death_announcements: true

ban_announcements:
    enable: true
    include_reason: false
    include_duration: true